language: R
sudo: false
cache: packages
r_packages:
  - covr
after_success:
  - Rscript -e 'covr::codecov()'

addons:
  apt:
    packages:
      - libhiredis-dev
      - redis-server

services:
  - redis-server

# Until I push some changes to CRAN
r_github_packages:
  - richfitz/redux
