language: R
sudo: false
cache: packages
r_packages:
  - covr
after_success:
  - Rscript -e 'covr::codecov()'

deploy:
  provider: script
  script: ./docker/travis
  on:
    all_branches: true

addons:
  apt:
    packages:
      - libhiredis-dev
      - redis-server

services:
  - redis-server

r_github_packages:
  - richfitz/heartbeatr
